# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: templates/variable-reuse.yml

steps:
  - script: echo ${{ format('My favorite veggie {0}', variables.favoriteVeggie) }}
    displayName: Template expression functions
  - script: echo my favorite vegetable is ${{ variables.favoriteVeggie }}
    displayName: Get variable from template
  - template: templates/simple-param.yml  # Template reference
    parameters:
      yesNo: false
  - template: templates/enforce-parameter.yml
    parameters:
      solution: mysolution
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "JaCoCo"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
      failIfCoverageEmpty: true
